// Better Auth official schema - generated by @better-auth/cli
import { pgTable, text, timestamp, boolean, integer, decimal, date, json } from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  firstNames: text("first_names").notNull(),
  lastNames: text("last_names").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  role: text("role").notNull().default("doctor"), // "admin", "doctor", or "secretary"
  isActive: boolean("is_active").default(true).notNull(),
  phone: text("phone"),
  speciality: text("speciality"), // For doctors
  licenseNumber: text("license_number"), // For doctors (e.g., "MN-12345")
  department: text("department"), // Department/area for any user
  description: text("description"), // Bio/description for doctors
  education: text("education"), // Education/training background
  certifications: text("certifications"), // Certifications (stored as comma-separated or JSON)
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => new Date())
    .notNull(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

// Medical Records Schema

// Patients table - reusable patient information
export const patient = pgTable("patient", {
  id: text("id").primaryKey(),
  fullName: text("full_name").notNull(),
  idNumber: text("id_number").notNull().unique(), // Cédula
  insuranceType: text("insurance_type"), // Tipo de seguro
  phone: text("phone"),
  email: text("email"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

// Main medical record
export const medicalRecord = pgTable("medical_record", {
  id: text("id").primaryKey(),
  patientId: text("patient_id")
    .notNull()
    .references(() => patient.id, { onDelete: "cascade" }),
  doctorId: text("doctor_id")
    .notNull()
    .references(() => user.id, { onDelete: "restrict" }),
  recordDate: date("record_date").notNull(),

  // Biometric data
  age: integer("age").notNull(),
  weight: decimal("weight", { precision: 5, scale: 2 }), // kg
  height: decimal("height", { precision: 5, scale: 2 }), // cm
  bmi: decimal("bmi", { precision: 4, scale: 2 }), // calculated

  // Vital signs
  bloodPressure: text("blood_pressure"), // e.g., "120/80"
  heartRate: integer("heart_rate"), // bpm
  oxygenSaturation: integer("oxygen_saturation"), // %
  temperature: decimal("temperature", { precision: 4, scale: 2 }), // °C

  // Consultation
  consultationReason: text("consultation_reason").notNull(),
  cie10Code: text("cie10_code"), // Diagnosis code
  currentIllness: text("current_illness"),
  illnessEvolution: text("illness_evolution"),

  // Personal history
  cardiovascularRiskFactors: json("cardiovascular_risk_factors").$type<string[]>(), // Array of risk factors
  cardiovascularHistory: text("cardiovascular_history"),
  personalPathologicalHistory: text("personal_pathological_history"),
  surgicalHistory: text("surgical_history"),
  habitualMedication: json("habitual_medication").$type<string[]>(), // Array of medications
  allergies: text("allergies"),
  familyPathologicalHistory: text("family_pathological_history"),

  // System review (Examen por sistemas)
  skinAndAppendages: text("skin_and_appendages"),
  respiratorySystem: text("respiratory_system"),
  cardiovascularSystem: text("cardiovascular_system"),
  gastrointestinalSystem: text("gastrointestinal_system"),
  genitourinarySystem: text("genitourinary_system"),
  musculoskeletalSystem: text("musculoskeletal_system"),
  endocrineSystem: text("endocrine_system"),
  neurologicalSystem: text("neurological_system"),

  // Physical exam
  generalInspection: text("general_inspection"),
  glasgowScale: text("glasgow_scale"),
  neck: text("neck"),
  thorax: text("thorax"),
  heart: text("heart"),
  lungs: text("lungs"),
  abdomen: text("abdomen"),
  upperExtremities: text("upper_extremities"),
  lowerExtremities: text("lower_extremities"),

  // Studies performed
  studiesPerformed: json("studies_performed").$type<string[]>(), // Array of study types
  studiesResults: text("studies_results"),

  // Treatment plan
  followUpDate: date("follow_up_date"),
  rest: text("rest"),
  diet: text("diet"),
  physicalActivity: text("physical_activity"),
  alarmSigns: text("alarm_signs"),
  additionalStudies: json("additional_studies").$type<string[]>(), // Array of study types

  // Medications prescribed
  prescribedMedications: json("prescribed_medications").$type<string[]>(), // Array of medication names
  treatmentObservations: text("treatment_observations"),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});
